In [1]:
import os
os.chdir(os.getcwd() + '/../../')

In [2]:
import pandas as pd
import numpy as np
import re

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC, SVC
from sklearn.metrics import confusion_matrix

from scripts.utils import *

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\PendragonS\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\PendragonS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [3]:
comments = pd.read_csv('data/comments/preprocessed_comments.csv', index_col=0)
comments = comments.dropna()
comments.head()

   toxic                                       comment_text
0      0  explanation why the edits make under my userna...
1      0  d'aww ! he match this background colour i be s...
2      0  hey man , i be really not try to edit war . it...
3      0  `` more i can not make any real suggestion on ...
4      0  you , sir , be my hero . any chance you rememb...

# 1. TF-IDF

In [4]:
# vectorization
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(comments['comment_text'])
y = comments['toxic']

# train val, test split
X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=0)
X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.2, stratify=y_temp, random_state=0)

In [5]:
# ONLY TOXIC

terms = vectorizer.get_feature_names()

# sum tfidf frequency of each term through documents
means = X[y==1].mean(axis=0)

# connecting term to its sums frequency
data = []
for col, term in enumerate(terms):
    data.append( (term, means[0,col] ))

ranking = pd.DataFrame(data, columns=['term','mean'])
ranking = ranking.sort_values('mean', ascending=False)
ranking.to_csv('data/comments/toxic_tfidf_rank_unigram.csv')
display(ranking.iloc[:10])

             term      mean
64975        fuck  0.064007
142653       shit  0.021041
150875       suck  0.018965
94297        like  0.016618
26602       bitch  0.016268
150288     stupid  0.015156
171694  wikipedia  0.014304
86599        just  0.013693
149573       stop  0.013346
19828     asshole  0.013079

In [6]:
# ONLY NON-TOXIC

terms = vectorizer.get_feature_names()

# sum tfidf frequency of each term through documents
means = X[y==0].mean(axis=0)

# connecting term to its sums frequency
data = []
for col, term in enumerate(terms):
    data.append( (term, means[0,col] ))

ranking = pd.DataFrame(data, columns=['term','mean'])
ranking = ranking.sort_values('mean', ascending=False)
ranking.to_csv('data/comments/non_toxic_tfidf_rank_unigram.csv')
display(ranking.sort_values('mean', ascending=False).iloc[:10])

             term      mean
19010     article  0.027063
117362       page  0.024510
153745       talk  0.022387
171694  wikipedia  0.018847
53932        edit  0.015978
86599        just  0.013288
165101        use  0.013194
97965        make  0.013064
155981     thanks  0.012260
156863      think  0.012170